---
- hosts: localhost
  gather_facts: true
  become_user: root
  connection: ssh
  tasks:
    - name: install package docker
      apt: name=docker.io state=present
    - name: create a file 
      file: dest=/opt/raj.txt state=touch
    - name: execute command
      command: ls -la /opt
